### ISSUE TITLE
Doesn't work with 2018 edition

### ISSUE THREAD

**Issue by youssefhabri** [zeyla/urbandictionary.rs#4]
As the title says, the crate doesn't seem to work with the 2018 edition of rust.

I get this error when I try to use it:
![screenshot from 2019-02-13 13-41-44](https://user-images.githubusercontent.com/1578005/52712579-538ea280-2f95-11e9-9b0b-5eaef219965b.png)

The code is the same as the `reqwest` example:
```rust
use reqwest::Client;
use std::error::Error;
use urbandictionary::ReqwestUrbanDictionaryRequester;

fn try_main() -> Result<(), Box<Error>> {
    let client = Client::new();
    let response = client.define("cat")?;

    if let Some(definition) = response {
        println!("The definition of cat is: {}", definition.definition);
    } else {
        println!("No definition found");
    }

    Ok(())
}

fn main() {
    try_main().unwrap();
}
```

**Comment by zeyla** [comment]
Hi, thanks for the issue and PR. I've updated the library to use Rust 1.39's async/await feature and have released an alpha version: https://crates.io/crates/urbandictionary/0.4.0-alpha.1

It will be 0.4 once Rust 1.39 lands in stable.
